"""deleted hello model

Revision ID: 646ced3ff7d9
Revises: 7988be0602ad
Create Date: 2024-09-23 14:20:06.508166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646ced3ff7d9'
down_revision: Union[str, None] = '7988be0602ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hellos_id', table_name='hellos')
    op.drop_index('ix_hellos_title', table_name='hellos')
    op.drop_table('hellos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hellos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='hellos_pkey')
    )
    op.create_index('ix_hellos_title', 'hellos', ['title'], unique=False)
    op.create_index('ix_hellos_id', 'hellos', ['id'], unique=False)
    # ### end Alembic commands ###
